import { AgendaTemplate } from '../types';

export const DEFAULT_AGENDA_TEMPLATE: AgendaTemplate = {
  items: [
    {
      time: '7:00',
      programEvent: 'President Calls Meeting to Order',
      person: '',
      description: 'Welcome members and guests',
      roleKey: 'President',
    },
    {
      time: '',
      programEvent: 'Pledge',
      person: '',
      description: 'Lead the pledge',
      roleKey: 'Pledge',
    },
    {
      time: '',
      programEvent: 'Thought of the Day',
      person: '',
      description: 'Share an inspiring thought',
      roleKey: 'Thought of the Day',
    },
    {
      time: '',
      programEvent: 'Introduction of the Toastmaster',
      person: '',
      description: 'President introduces Toastmaster',
      roleKey: 'President',
    },
    {
      time: '7:05',
      programEvent: 'Toastmaster Introduces "functionary" roles',
      person: '',
      description: 'Introduce theme and functionaries',
      roleKey: 'Toastmaster',
    },
    {
      time: '',
      programEvent: 'Grammarian',
      person: '',
      description: '30-second description + WOD',
      roleKey: 'Grammarian',
    },
    {
      time: '',
      programEvent: 'Timer',
      person: '',
      description: '30-second description',
      roleKey: 'Timekeeper',
    },
    {
      time: '',
      programEvent: 'Ah Counter',
      person: '',
      description: '30-second description of duties',
      roleKey: 'Ah-Counter',
    },
    {
      time: '',
      programEvent: 'Ballot Vote Counter',
      person: '',
      description: '30-second description of duties',
      roleKey: 'Ballot Counter',
    },
    {
      time: '7:10',
      programEvent: 'Table Topics Master Introduced!',
      person: '',
      description: 'Directs impromptu questions (10-15 minutes)',
      roleKey: 'Table Topics Master',
    },
    {
      time: '',
      programEvent: 'Vote for Best Table Topics speaker',
      person: '',
      description: 'Vote for best Table Topics speaker',
      roleKey: '',
    },
    {
      time: '7:20',
      programEvent: 'Toastmaster Introduces Speakers',
      person: '',
      description: 'Speaking portion of the meeting',
      roleKey: 'Toastmaster',
    },
    {
      time: '',
      programEvent: 'Evaluator #1 Reads Objectives',
      person: '',
      description: '30-45 seconds (Reads Objectives)',
      roleKey: 'Evaluator 1',
    },
    {
      time: '',
      programEvent: 'Speaker #1',
      person: '',
      description: 'Insert Title / 5-7 Mins',
      roleKey: 'Speaker 1',
    },
    {
      time: '',
      programEvent: 'Evaluator #2 Reads Objectives',
      person: '',
      description: '30-45 seconds (Reads Objectives)',
      roleKey: 'Evaluator 2',
    },
    {
      time: '',
      programEvent: 'Speaker #2',
      person: '',
      description: 'Insert Title / 5-7 Mins',
      roleKey: 'Speaker 2',
    },
    {
      time: '',
      programEvent: 'Evaluator #3 Reads Objectives',
      person: '',
      description: '30-45 seconds (Reads Objectives)',
      roleKey: 'Evaluator 3',
    },
    {
      time: '',
      programEvent: 'Speaker #3',
      person: '',
      description: 'Insert Title / 5-7 Mins',
      roleKey: 'Speaker 3',
    },
    {
      time: '',
      programEvent: 'Vote for Best Speech',
      person: '',
      description: 'Vote for best speech',
      roleKey: '',
    },
    {
      time: '7:55',
      programEvent: 'General Evaluator is Introduced',
      person: '',
      description: 'Coordinates evaluation phase',
      roleKey: 'General Evaluator',
    },
    {
      time: '',
      programEvent: 'Evaluator #1',
      person: '',
      description: '2-3 mins',
      roleKey: 'Evaluator 1',
    },
    {
      time: '',
      programEvent: 'Evaluator #2',
      person: '',
      description: '2-3 mins',
      roleKey: 'Evaluator 2',
    },
    {
      time: '',
      programEvent: 'Evaluator #3',
      person: '',
      description: '2-3 mins',
      roleKey: 'Evaluator 3',
    },
    {
      time: '',
      programEvent: 'Timer Report',
      person: '',
      description: '30-second report',
      roleKey: 'Timekeeper',
    },
    {
      time: '',
      programEvent: 'Ah Counter Report',
      person: '',
      description: '30-second report',
      roleKey: 'Ah-Counter',
    },
    {
      time: '',
      programEvent: 'Grammarian Report',
      person: '',
      description: '90-second report',
      roleKey: 'Grammarian',
    },
    {
      time: '8:03',
      programEvent: 'General Evaluator Comments',
      person: '',
      description: 'Overall evaluation of the meeting - 2-3 mins',
      roleKey: 'General Evaluator',
    },
    {
      time: '',
      programEvent: 'Awards – Vote Counter',
      person: '',
      description: '',
      roleKey: 'Ballot Counter',
    },
    {
      time: '',
      programEvent: 'Best Table Topic',
      person: '',
      description: '',
      roleKey: '',
    },
    {
      time: '',
      programEvent: 'Best Evaluator',
      person: '',
      description: '',
      roleKey: '',
    },
    {
      time: '',
      programEvent: 'Best Speaker',
      person: '',
      description: '',
      roleKey: '',
    },
    {
      time: '',
      programEvent: 'Inspiration Award',
      person: '',
      description: 'Awarded by current or past president',
      roleKey: 'Inspiration Award',
    },
    {
      time: '8:07',
      programEvent: 'Toastmaster\'s Closing Remarks',
      person: '',
      description: '',
      roleKey: 'Toastmaster',
    },
    {
      time: '8:09',
      programEvent: 'President\'s Closing Comments',
      person: '',
      description: 'Announcements/schedule review',
      roleKey: 'President',
    },
    {
      time: '',
      programEvent: 'Member Recognition',
      person: '',
      description: 'Outside speaking engagements',
      roleKey: '',
    },
    {
      time: '',
      programEvent: 'Guest Comments',
      person: '',
      description: '',
      roleKey: '',
    },
    {
      time: '8:15',
      programEvent: 'Adjourn Meeting (President)',
      person: '',
      description: '',
      roleKey: 'President',
    },
  ],
};

// Template for meetings with only 2 speakers
export const TWO_SPEAKER_TEMPLATE: AgendaTemplate = {
  items: DEFAULT_AGENDA_TEMPLATE.items.filter(item => 
    !item.programEvent.includes('Speaker #3') && 
    !item.programEvent.includes('Evaluator #3')
  ),
};
